### PR TITLE
Ux improvement

### PR DESCRIPTION
**Pull request by luxcem**
Hi, here is a couple of UX improvements I use with your extension.
The improvements are :
- MultiSelect form fields (I use the bootstrap-select component : https://github.com/silviomoreto/bootstrap-select writen by silviomoreto )
- AuthItem names appear in grid view in addition to the description
- AuthItem description appear in assignement grid view
- User filter in AuthAssignement grid view (based on User->username)
- Column filter in AuthItem view (I use the table-filter js https://github.com/hail2u/jquery.table-filter writen by hail2u )

### CODE REVIEW

**Comment by cniska** [comment]
This is nice but I need to try it out before I merge it. Could you please create a new PR to a new branch called `ux-improvement` (I'll create it now).

**Comment by cniska** [comment]
Closed by mistake, I'll keep this open for now.

**Comment by cniska** [comment]
Done, please create the PR when you have time.

**Comment by luxcem** [comment]
Closing the PR, feel free to reuse the code if you want.

**Pull request closed without merging**
